apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: root-app
    app.kubernetes.io/part-of: vpm-mini
    app.kubernetes.io/component: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/HirakuArai/vpm-mini.git
    targetRevision: main
    path: infra/gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: hyper-swarm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m