apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-queueproxy
  namespace: default
  labels:
    release: vpm-mini-kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app: hello-queueproxy-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scheme: http
