version: "3.9"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  image: vpm-mini/app:dev
  restart: unless-stopped
  environment:
    - ROLE=
  healthcheck:
    # S4で /healthz に差し替え予定。暫定は常に0でOKな軽量チェック
    test: ["CMD","python","-c","print(200)"]
    interval: 10s
    timeout: 3s
    retries: 5
  deploy:
    replicas: 1

services:
  watcher:
    <<: *app
    environment:
      - ROLE=watcher
  curator:
    <<: *app
    environment:
      - ROLE=curator
  planner:
    <<: *app
    environment:
      - ROLE=planner
  synthesizer:
    <<: *app
    environment:
      - ROLE=synthesizer
  archivist:
    <<: *app
    environment:
      - ROLE=archivist