#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, os, sys, glob, subprocess, shlex, re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASK_DIRS = [ROOT / "reports" / "ask", ROOT / "reports" / "admin" / "ask"]
THINK_DIR = ROOT / "reports" / "think"

def run(args, check=True, capture=False):
    p = subprocess.run(args, text=True, capture_output=capture)
    if check and p.returncode != 0:
        sys.stderr.write(p.stderr or "")
        raise SystemExit(p.returncode)
    return p.stdout if capture else p.returncode

def latest_ask(issue: str|None) -> Path:
    cand = []
    for d in ASK_DIRS:
        if d.exists(): cand += sorted(d.glob("ask_*.json"))
    if not cand: sys.exit("no reports/ask/ask_*.json found")
    if issue:
        for p in reversed(cand):
            try:
                if str(json.loads(p.read_text()).get("meta",{}).get("issue")) == str(issue):
                    return p
            except Exception: pass
    return cand[-1]

def allow_ok(argv: list[str]) -> bool:
    if not argv: return False
    cmd = argv[0]
    if cmd == "kubectl":
        return any(x in argv[1:2] for x in ("get","describe","apply","wait"))
    if cmd in ("curl","echo"): return True
    return False

def exec_plan(cmds: list[list[str]], dry: bool, prnum: str, ts: str) -> Path:
    THINK_DIR.mkdir(parents=True, exist_ok=True)
    log = THINK_DIR / f"exec_{ts}.log"
    with log.open("w", encoding="utf-8") as fw:
        for c in cmds:
            if isinstance(c,str): c = shlex.split(c)
            line = " ".join(shlex.quote(x) for x in c)
            fw.write(f"$ {line}\n")
            if not allow_ok(c):
                fw.write("  [skip] not in allowlist\n\n"); continue
            if dry:
                fw.write("  [dry-run]\n\n"); continue
            p = subprocess.run(c, text=True, capture_output=True)
            fw.write((p.stdout or "") + (p.stderr or "") + "\n")
    run(["git","add", str(log.relative_to(ROOT))], check=False)
    run(["git","commit","-m",f"think: exec log {ts}"], check=False)
    run(["git","push"], check=False)
    run(["gh","pr","comment", prnum, "--body", f"Exec log: `{log.relative_to(ROOT)}`"], check=False)
    return log

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--issue")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--execute", action="store_true")
    args = ap.parse_args()

    ask = latest_ask(args.issue)
    obj = json.loads(ask.read_text())
    understanding = str(obj.get("understanding","") or "")
    raw = (obj.get("plan") or {}).get("commands") or []
    cmds = [shlex.split(x) if isinstance(x,str) else [str(y) for y in x] for x in raw]

    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
    THINK_DIR.mkdir(parents=True, exist_ok=True)
    plan_md = THINK_DIR / f"plan_{ts}.md"
    think_json = THINK_DIR / f"think_{ts}.json"
    body_md = THINK_DIR / f"body_{ts}.md"

    plan_md.write_text(
        f"# plan {ts}\n\nsource_ask: `{ask.relative_to(ROOT)}`\n\n## understanding\n{understanding}\n\n## plan.commands\n" +
        "".join(f"- `{' '.join(shlex.quote(t) for t in c)}`\n" for c in cmds),
        encoding="utf-8"
    )
    think_json.write_text(json.dumps({
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_ask": str(ask.relative_to(ROOT)),
        "issue": args.issue, "dry_run": bool(args.dry_run),
        "plan": {"commands": [" ".join(c) for c in cmds]},
        "understanding": understanding
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    body_md.write_text(
        "Draft plan generated by Thinker.\n\n"
        f"- source_ask: `{ask.relative_to(ROOT)}`\n"
        f"- dry_run: {args.dry_run}\n", encoding="utf-8"
    )

    run(["git","fetch","origin","--quiet"], check=False)
    run(["git","switch","-q","main"], check=False); run(["git","pull","--ff-only","--quiet"], check=False)
    br = f"think/plan-{ts}"
    run(["git","switch","-c", br])
    run(["git","add", str(plan_md.relative_to(ROOT))])
    run(["git","commit","-m",f"think: plan {ts} (draft via thinker)"])
    run(["git","push","-u","origin","HEAD"])

    # gh pr create（JSONなし互換）→URLから番号を抜く→取れなければ --head で照会
    out = run(["gh","pr","create",
               "-t", f"think: plan {ts}",
               "-d", "--body-file", str(body_md),
               "-H", br, "-B", "main"], capture=True, check=False)
    prnum = ""
    if isinstance(out,str):
        m = re.search(r"/pull/(\\d+)", out);  prnum = m.group(1) if m else ""
    if not prnum:
        prnum = run(["gh","pr","list","--head", br, "--json","number","-q",".[0].number"],
                    capture=True, check=False).strip()
    if not prnum: sys.exit("[thinker] failed to obtain PR number")

    if args.execute and cmds:
        exec_plan(cmds, args.dry_run, prnum, ts)

if __name__ == "__main__":
    sys.exit(main() or 0)
