apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: monitoring-secretstore
  namespace: monitoring
spec:
  provider:
    kubernetes:
      remoteNamespace: monitoring
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: "external-secrets-sa"
