apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-ai
  namespace: hyper-swarm
spec:
  template:
    metadata:
      labels:
        app: hello-ai
    spec:
      containers:
      - image: ghcr.io/hirakuarai/vpm-mini/hello-ai:latest
        ports:
        - containerPort: 8080
          name: http1
