apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: hyper-swarm
  labels:
    app: pushgateway
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
        component: monitoring
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:v1.9.0
        ports:
        - containerPort: 9091
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9091
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9091
          initialDelaySeconds: 5
          periodSeconds: 10