apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: hyper-swarm
  labels:
    app: pushgateway
    component: monitoring
spec:
  type: ClusterIP
  selector:
    app: pushgateway
  ports:
  - name: http
    port: 9091
    targetPort: 9091
    protocol: TCP