apiVersion: v1
kind: Pod
metadata:
  name: planner-debug
  namespace: hyper-swarm
  annotations:
    spiffe.io/inject: "true"
spec:
  serviceAccountName: planner-sa
  containers:
  - name: debug
    image: alpine:3.19
    command:
    - /bin/sh
    - -c
    - |
      echo "SPIRE Test Pod Started"
      while true; do
        sleep 30
        echo "Checking SPIRE socket..."
        ls -la /run/spire/sockets/agent.sock 2>/dev/null || echo "Socket not found"
      done
    volumeMounts:
    - name: spire-agent-socket
      mountPath: /run/spire/sockets
      readOnly: true
  volumes:
  - name: spire-agent-socket
    hostPath:
      path: /run/spire/sockets
      type: DirectoryOrCreate