apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: hello-ai-routes
  namespace: monitoring
  labels:
    release: vmp-mini-kube-prometheus-stack
spec:
  route:
    groupBy: ['alertname','namespace']
    groupWait: 30s
    groupInterval: 2m
    repeatInterval: 2h
    receiver: 'slack'
  receivers:
  - name: 'slack'
    slackConfigs:
    - apiURL:
        name: am-slack-receiver
        key: SLACK_WEBHOOK_URL
      sendResolved: true
      channel: '#alerts'
      title: '[{{ .Status }}] {{ .CommonLabels.alertname }}'
      text: '{{ range .Alerts }}*{{ .Labels.severity | toUpper }}*: {{ .Annotations.summary }} {{ "\n" }}{{ end }}'
