apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hello-ai-slo
  namespace: monitoring
  labels: { release: vpm-mini-kube-prometheus-stack }
spec:
  groups:
  - name: hello-ai-slo-recordings
    rules:
    # p95 latency (5m window)
    - record: hello_ai:latency:p95:5m
      expr: |
        histogram_quantile(
          0.95,
          sum by (le) (rate(hello_ai_request_duration_seconds_bucket[5m]))
        )
    # error rate % (5m window)
    - record: hello_ai:error_rate:5m
      expr: |
        ( sum(rate(hello_ai_requests_total{code=~"5.."}[5m])) /
          sum(rate(hello_ai_requests_total[5m])) ) * 100

  - name: hello-ai-slo-alerts
    rules:
    - alert: HelloAI_SLO_P95_Breach
      expr: hello_ai:latency:p95:5m > 1
      for: 10m
      labels: { severity: warning, slo: p95_lt_1s }
      annotations:
        summary: "hello-ai p95 latency SLO breach"
        description: "p95 > 1s for 10m (current={{ $value | printf \"%.3fs\" }})"
    - alert: HelloAI_SLO_ErrorRate_Breach
      expr: hello_ai:error_rate:5m > 1
      for: 10m
      labels: { severity: warning, slo: error_lt_1pct }
      annotations:
        summary: "hello-ai error rate SLO breach"
        description: "5xx error > 1% for 10m (current={{ $value | printf \"%.2f%%\" }})"