apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: curator-slo
  namespace: monitoring
  labels: { release: vpm-mini-kube-prometheus-stack }
spec:
  groups:
  - name: curator-availability
    rules:
    - alert: Curator_ServiceDown
      expr: avg_over_time(hello_ai_up{job="curator"}[5m]) < 0.5
      for: 5m
      labels: { severity: critical }
      annotations:
        summary: "curator down"
        description: "hello_ai_up < 0.5 (5m)"
  - name: curator-performance
    rules:
    - alert: Curator_HighLatency
      expr: histogram_quantile(0.95, sum by (le) (rate(hello_ai_request_duration_seconds_bucket{job="curator"}[5m]))) > 1
      for: 10m
      labels: { severity: warning }
      annotations:
        summary: "curator p95 latency high"
        description: "p95 > 1s for 10m"
    - alert: Curator_HighErrorRate
      expr: (sum(rate(hello_ai_requests_total{job="curator",code=~"5.."}[5m])) / sum(rate(hello_ai_requests_total{job="curator"}[5m]))) * 100 > 1
      for: 10m
      labels: { severity: warning }
      annotations:
        summary: "curator error rate high"
        description: "5xx error > 1% (5m)"
