apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dummy-sm
  namespace: monitoring-dev
spec:
  selector: {matchLabels: {app: dummy}}
  endpoints:
    - port: http
      interval: 30s
