apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-sm
  namespace: monitoring-dev
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app: hello
  endpoints:
    - port: http
      interval: 30s
