project_id: vpm-mini
phase: Phase 2
state_path: STATE/current_state.md
evidence_glob: reports/evidence_*.md
ruleset_required:
- k8s-validate
- knative-ready
- evidence-dod
branch_required: []
goals:
  short: P2-6（監視ライン拡張：ServiceMonitor/PromRule 構文OK＋Evidence）
  mid: サービス移植 / Autoscale PoC
  long: 小規模Swarm安定 + KPI閾値達成
