project_id: vpm-mini
phase: Phase 2
state_path: STATE/current_state.md
evidence_glob: reports/evidence_*.md
ruleset_required:
- k8s-validate
- knative-ready
- evidence-dod
branch_required: []
goals:
  short: P2-5（Autoscale PoC：min=0 / max=30 の挙動を記録）
  mid: サービス移植 / Autoscale PoC
  long: 小規模Swarm安定 + KPI閾値達成
