apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire-system
spec:
  type: ClusterIP
  selector:
    app: spire-server
  ports:
  - name: grpc
    port: 8081
    targetPort: 8081
    protocol: TCP