apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-k8s-workload-registrar
  namespace: spire-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-k8s-workload-registrar
  template:
    metadata:
      labels:
        app: spire-k8s-workload-registrar
    spec:
      serviceAccountName: spire-workload-registrar
      containers:
      - name: k8s-workload-registrar
        image: ghcr.io/spiffe/k8s-workload-registrar:1.8.0
        args:
        - -config
        - /run/spire/config/registrar.conf
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config
          mountPath: /run/spire/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: k8s-workload-registrar