apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireSpireSocket
metadata:
  name: must-have-spire-socket
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: 
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "gatekeeper-system"
      - "spire-system"
      - "local-path-storage"
  parameters:
    exemptNamespaces:
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "gatekeeper-system"
      - "spire-system"
      - "local-path-storage"