apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpm-mini-kube-state-metrics
  namespace: argocd
spec:
  project: vpm-mini-dev
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-state-metrics
    targetRevision: 5.16.0
    helm:
      values: |
        image:
          pullPolicy: IfNotPresent
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true