apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-cm
    app.kubernetes.io/part-of: argocd
data:
  service.stdout: |
    name: stdout
    type: webhook
    url: http://localhost  # ダミー。実体はcontrollerログ出力
    headers:
      - name: X-Dummy
        value: ok
  template.app-sync-status: |
    message: |
      [{{.app.metadata.name}}] status={{.app.status.sync.status}} health={{.app.status.health.status}}
  trigger.on-change: |
    - when: app.status.health.status in ['Degraded'] or app.status.sync.status in ['OutOfSync']
      send: [app-sync-status]
      to: [stdout]