# This Pod should be DENIED by RequireServiceAccount constraint
apiVersion: v1
kind: Pod
metadata:
  name: deny-no-serviceaccount
  namespace: hyper-swarm
spec:
  containers:
  - name: test
    image: alpine:3.19
    command:
    - /bin/sh
    - -c
    - "sleep 3600"