apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rougel-exporter
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - name: app
        image: gcr.io/knative-samples/helloworld-go
        env:
        - name: TARGET
          value: rougel-exporter
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
      enableServiceLinks: false
      timeoutSeconds: 300
