#!/usr/bin/env bash
set -euo pipefail

KSVC_YAML="${1:-/tmp/ksvc_ready.yaml}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTPUT_FILE="reports/evidence_kservice_ready_${TIMESTAMP}.md"

mkdir -p reports

if [ ! -f "$KSVC_YAML" ]; then
  echo "::error::KSVC YAML file not found: $KSVC_YAML"
  exit 1
fi

echo "Generating evidence from $KSVC_YAML..."

KSVC_NAME=$(grep 'name:' "$KSVC_YAML" | head -1 | awk '{print $2}')
READY_STATUS=$(grep -A 10 'type: Ready' "$KSVC_YAML" | grep 'status:' | head -1 | awk '{print $2}' || echo "Unknown")
READY_REASON=$(grep -A 10 'type: Ready' "$KSVC_YAML" | grep 'reason:' | head -1 | awk '{print $2}' || echo "N/A")
URL=$(grep 'url:' "$KSVC_YAML" | head -1 | awk '{print $2}' || echo "N/A")

cat > "$OUTPUT_FILE" <<EOF
# Knative Service READY Evidence

**Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Service**: $KSVC_NAME
**KSVC YAML**: $KSVC_YAML

## Ready Status

- **Ready**: $READY_STATUS
- **Reason**: $READY_REASON
- **URL**: $URL

## Full Conditions

\`\`\`yaml
$(grep -A 50 'conditions:' "$KSVC_YAML" || echo "No conditions found")
\`\`\`

## Verification

- READY status extracted: $READY_STATUS
- Expected: True
- Result: $([ "$READY_STATUS" = "True" ] && echo "✅ PASS" || echo "❌ FAIL")

---
🤖 Generated by gen_evidence_kservice_ready.sh
EOF

echo "✅ Evidence generated: $OUTPUT_FILE"
cat "$OUTPUT_FILE"