apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: watcher
  namespace: hyper-swarm
  labels:
    app: watcher
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: '10'
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '30'
    spec:
      containers:
      - name: watcher
        image: ghcr.io/hirakuarai/hello-ai:1.0.3
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8001
          initialDelaySeconds: 2
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: '1'
            memory: 512Mi
        envFrom:
        - configMapRef:
            name: watcher-config
