apiVersion: v1
kind: Service
metadata:
  name: watcher-metrics
  namespace: hyper-swarm
  labels: 
    app: watcher
spec:
  selector: 
    app: watcher
  ports:
  - name: http-metrics
    port: 9001
    targetPort: 9001
