from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict


def iso_now() -> str:
    """Return current time with timezone offset in ISO8601."""
    return datetime.now().astimezone().isoformat(timespec="seconds")


def build_lane_status(project_id: str) -> Dict[str, Any]:
    """Construct a minimal lane_status_v1 payload for vpm-mini Layer B."""
    now = iso_now()
    request_id = f"req-{now}"

    payload_data: Dict[str, Any] = {
        "kind": "lane_status_v1",
        "project_id": project_id,
        "lane": {"layer": "layer_b", "name": "doc_update"},
        "as_of": now,
        "cycle": {
            "latest_cycle_id": "cycle-1",
            "status": "completed",
            "started_at": "2025-11-28T00:00:00+09:00",
            "completed_at": "2025-11-29T00:00:00+09:00",
            "steps": {
                "aya": {
                    "status": "completed",
                    "latest_entry": {
                        "blackboard_issue": 841,
                        "blackboard_comment_id": 0,
                        "actions_workflow": "Doc Update Proposal (PM)",
                        "actions_run_id": 0,
                        "artifact_path": "reports/doc_update_proposals/2025-11-28-vpm-mini.json",
                        "updated_at": "2025-11-28T12:00:00+09:00",
                        "summary": "STATE/vpm-mini/current_state.md の Layer B セクション更新案を生成。",
                    },
                },
                "sho": {
                    "status": "completed",
                    "latest_entry": {
                        "actions_workflow": "Doc Update Review (Sho v2)",
                        "actions_run_id": 0,
                        "artifact_path": "reports/doc_update_reviews/2025-11-28-vpm-mini.json",
                        "review_mode": "auto_accept_v1",
                        "risk": "low",
                        "updated_at": "2025-11-28T13:00:00+09:00",
                        "summary": "提案を auto-accept v1 (risk=low) と判定。",
                    },
                },
                "tsugu": {
                    "status": "completed",
                    "latest_entry": {
                        "apply_mode": "codex_apply",
                        "prs": [
                            {
                                "number": 847,
                                "title": "Apply: Layer B rules v1 (STATE)",
                                "state": "merged",
                            },
                            {
                                "number": 849,
                                "title": "Apply: Evidence & Gap update",
                                "state": "merged",
                            },
                        ],
                        "updated_at": "2025-11-29T10:00:00+09:00",
                        "summary": "STATE/vpm-mini/current_state.md を提案どおり置き換え。",
                    },
                },
            },
        },
        "state_view": {
            "state_file": "STATE/vpm-mini/current_state.md",
            "section_anchor": "#layer-b-doc-update-v1",
            "digest": "Layer B 最小サイクル（Aya→Sho→Tsugu/Apply→STATE更新）が cycle-1 まで完了。",
            "known_gaps": [
                "Gen / PM Snapshot への連携は未実装。",
                "Kai 自身はまだ ChatGPT 上の概念のみ。",
            ],
        },
        "next_suggested_actions": [
            {
                "id": "b-002",
                "title": "Gen / PM Snapshot を黒板レーンに接続。",
                "owner": "Kai",
                "priority": "M",
                "suggested_lane": "pm_snapshot",
            }
        ],
    }

    summary_md = (
        "## Layer B / doc_update status\n"
        "- cycle-1 completed; Aya/Sho/Tsugu steps recorded; PRs #847/#849 merged\n"
        "- state updated via doc_update; gaps: PM Snapshot integration pending; Kai is conceptual on ChatGPT"
    )

    response: Dict[str, Any] = {
        "version": "kai_response_v1",
        "request_id": request_id,
        "status": "ok",
        "meta": {"generated_at": now, "kai_version": "0.1.0"},
        "payload": {"kind": "lane_status_v1", "data": payload_data},
        "summary_md": summary_md,
        "notes": [
            "Sources: issue #841, PRs #847/#849, STATE/vpm-mini/current_state.md",
            "Generated by tools/kai/lane_status_v1.py (v1 minimal implementation)",
        ],
    }

    return response


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Kai-0 lane_status_v1 response."
    )
    parser.add_argument(
        "--project-id", required=True, help="Project ID (vpm-mini for v1)."
    )
    parser.add_argument(
        "--output",
        default="reports/kai/lane_status_v1.json",
        help="Output path for the kai_response_v1 JSON (default: reports/kai/lane_status_v1.json).",
    )
    args = parser.parse_args()

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    response = build_lane_status(project_id=args.project_id)
    output_path.write_text(
        json.dumps(response, indent=2, ensure_ascii=False), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
