name: Autopilot L1 — Manual Shim

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project namespace'
        required: false
        default: 'vpm-mini'
        type: string
      dry_run:
        description: 'Do not create PR (preview only)'
        required: false
        default: true
        type: boolean
      max_lines:
        description: 'Maximum lines per run'
        required: false
        default: '3'
        type: string

jobs:
  call-l1:
    permissions:
      contents: write
      pull-requests: write
      actions: read
    uses: ./.github/workflows/autopilot_l1.yml
    with:
      project: ${{ inputs.project }}
      dry_run: ${{ inputs.dry_run }}
      max_lines: ${{ inputs.max_lines }}
    secrets: inherit  # pragma: allowlist secret