name: auto-pr
on:
  push:
    branches-ignore: [ main ]
permissions:
  contents: write
  pull-requests: write
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/','')
            const { owner, repo } = context.repo
            const prs = await github.rest.pulls.list({ owner, repo, head: `${owner}:${branch}`, state: 'open' })
            if (prs.data.length === 0) {
              const { data: pr } = await github.rest.pulls.create({
                owner, repo, base: 'main', head: branch,
                title: `auto: ${branch}`,
                body: 'Auto-created PR (branch pushed without PR).'
              })
              core.info(`PR #${pr.number} created for ${branch}`)
            } else {
              core.info(`PR already exists for ${branch}`)
            }
