name: build_watcher
true:
  push:
    paths:
    - services/watcher/**
    - .github/workflows/build_watcher.yml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & Push
      uses: docker/build-push-action@v6
      with:
        context: services/
        file: services//Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: 'ghcr.io/hirakuarai/watcher:0.2.0

          ghcr.io/hirakuarai/watcher:latest

          '
        push: true
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository ||
      github.event_name == 'push' }}
permissions:
  contents: read
'on': {}
