name: build-metrics-echo-ghcr
on:
  push:
    branches: [ main ]
    paths:
      - "services/metrics-echo/**"
      - ".github/workflows/build_metrics-echo_ghcr.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Derive lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./services/metrics-echo
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/metrics-echo:latest
