name: build_archivist
on:
  push:
    paths:
      - "services/archivist/**"
      - ".github/workflows/build_archivist.yml"
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: services/archivist
          file: services/archivist/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            PORT=8005
          tags: |
            ghcr.io/${{ github.repository_owner }}/archivist:0.2.0
            ghcr.io/${{ github.repository_owner }}/archivist:latest
          push: true
