name: Build & Push hello-ai (GHCR) v3
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag (e.g. 1.0.3)"
        required: true
        default: "1.0.3"
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push (multi-arch)
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/hello-ai:${{ github.event.inputs.tag }}"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "$IMAGE" \
            -f services/hello-ai/Dockerfile services/hello-ai \
            --push
          echo "::notice ::IMAGE=$IMAGE"
