name: build_watcher
on:
  push:
    paths:
      - "services/watcher/**"
      - ".github/workflows/build_watcher.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: services/watcher
          file: services/watcher/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/hirakuarai/watcher:0.2.0
            ghcr.io/hirakuarai/watcher:latest
          push: true