name: build_planner
on:
  push:
    paths:
      - "services/planner/**"
      - ".github/workflows/build_planner.yml"
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: services/planner
          file: services/planner/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            PORT=8003
          tags: |
            ghcr.io/HirakuArai/planner:0.2.0
            ghcr.io/HirakuArai/planner:latest
          push: true
