name: Build & Push hello-ai (GHCR)
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag (e.g. 1.0.0)"
        required: true
        default: "1.0.0"
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HELLO_CONTEXT: services/hello-ai
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Derive lowercase owner
        id: who
        shell: bash
        run: |
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
      - name: Build & Push
        shell: bash
        run: |
          IMAGE=ghcr.io/${{ steps.who.outputs.owner_lc }}/hello-ai:${{ github.event.inputs.tag }}
          echo "IMAGE=$IMAGE"
          docker buildx build --progress=plain -t "$IMAGE" -f "$HELLO_CONTEXT/Dockerfile" "$HELLO_CONTEXT" --push
      - name: Evidence
        run: |
          echo "pushed=ghcr.io/${{ steps.who.outputs.owner_lc }}/hello-ai:${{ github.event.inputs.tag }}" | tee -a reports/ghcr_publish.txt