name: build_curator
on:
  push:
    paths:
      - "services/curator/**"
      - ".github/workflows/build_curator.yml"
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      PORT_CURATOR: 8002
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: services/curator
          file: services/curator/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            PORT=8002
          tags: |
            ghcr.io/${{ github.repository_owner }}/curator:0.2.0
            ghcr.io/${{ github.repository_owner }}/curator:latest
          push: true
