name: Build & Push hello-ai (GHCR) v4
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag (e.g. 1.0.5)"
        required: true
        default: "1.0.5"
  push:
    branches: [main]
    paths: ['services/hello-ai/**']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tag and commit
        id: meta
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="1.0.5"
          fi
          COMMIT_SHA="${{ github.sha }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "commit=$COMMIT_SHA" >> $GITHUB_OUTPUT

      - name: Build & Push (multi-arch)
        run: |
          TAG="${{ steps.meta.outputs.tag }}"
          COMMIT="${{ steps.meta.outputs.commit }}"
          IMAGE="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/hello-ai:$TAG"
          LATEST_IMAGE="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/hello-ai:latest"
          
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION="$TAG" \
            --build-arg GIT_COMMIT="$COMMIT" \
            -t "$IMAGE" \
            -t "$LATEST_IMAGE" \
            -f services/hello-ai/Dockerfile services/hello-ai \
            --push
          
          echo "::notice ::IMAGE=$IMAGE"
          echo "::notice ::LATEST=$LATEST_IMAGE"
