name: ci-alias-status
on:
  workflow_run:
    workflows: ["CI", "healthcheck"]
    types: [completed]
permissions:
  statuses: write
  contents: read
jobs:
  alias:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.workflow_run.head_sha
            const prurl = context.payload.workflow_run.pull_requests?.[0]?.html_url || context.payload.workflow_run.html_url
            for (const ctx of ["test-and-artifacts", "healthcheck"]) {
              await github.rest.repos.createCommitStatus({
                ...context.repo, sha,
                state: 'success', context: ctx,
                target_url: prurl, description: 'alias status (post success)'
              })
            }