name: evidence-pr-checks
on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
jobs:
  evidence-dod:
    if: contains(github.event.pull_request.labels.*.name, 'evidence')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check daily.md exists and has FOOTER
        run: |
          test -f reports/daily.md
          grep -q '^FOOTER:' reports/daily.md
  healthcheck:
    if: contains(github.event.pull_request.labels.*.name, 'evidence')
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  k8s-validate:
    if: contains(github.event.pull_request.labels.*.name, 'evidence')
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  knative-ready:
    if: contains(github.event.pull_request.labels.*.name, 'evidence')
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  test-and-artifacts:
    if: contains(github.event.pull_request.labels.*.name, 'evidence')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: echo verify note
        run: |
          awk '/^FOOTER:/{print; exit}' reports/daily.md || true
