name: Grafana Diagnostics
on:
  workflow_dispatch: {}
jobs:
  diag:
    env:
      GRAFANA_BASE_URL: ${{ vars.GRAFANA_BASE_URL || 'http://grafana.monitoring.svc.cluster.local' }}
      GRAFANA_API_TOKEN: ${{ secrets.GRAFANA_API_TOKEN }}
      GRAFANA_ORG_ID: ${{ vars.GRAFANA_ORG_ID || '1' }}
    runs-on: [self-hosted, k8s-runner]
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Load SSOT
        id: ssot
        run: |
          meta=$(cat infra/observability/dashboard_target.json)
          echo "org=$(jq -r '.grafana.org' <<<"$meta")" >> "$GITHUB_OUTPUT"
          echo "uid=$(jq -r '.grafana.uid' <<<"$meta")" >> "$GITHUB_OUTPUT"
          echo "slug=$(jq -r '.grafana.slug' <<<"$meta")" >> "$GITHUB_OUTPUT"
          echo "panel=$(jq -r '.grafana.panelId' <<<"$meta")" >> "$GITHUB_OUTPUT"

      - name: Echo config
        env:
          ORG: ${{ steps.ssot.outputs.org }}
          UID: ${{ steps.ssot.outputs.uid }}
          SLUG: ${{ steps.ssot.outputs.slug }}
          PANEL: ${{ steps.ssot.outputs.panel }}
          BASE: ${{ env.GRAFANA_BASE_URL }}
        run: |
          echo "BASE=$BASE"
          echo "ORG=$ORG UID=$UID SLUG=$SLUG PANEL=$PANEL"
          echo "RENDER_URL=${BASE%/}/render/d-solo/$UID/$SLUG?panelId=$PANEL&from=now-30m&to=now&orgId=$ORG"

      - name: API health check (no token)
        env:
          BASE: ${{ env.GRAFANA_BASE_URL }}
        run: |
          set -x
          curl -fsS -o /dev/null -w "no-token:/api/health HTTP=%{http_code}\n" "$BASE/api/health" || true

      - name: API health check (with token if present)
        env:
          BASE: ${{ env.GRAFANA_BASE_URL }}
          ORG: ${{ env.GRAFANA_ORG_ID }}
          TOKEN: ${{ env.GRAFANA_API_TOKEN }}
        run: |
          set -x
          if [ -n "${TOKEN:-}" ]; then
            curl -fsS -o /dev/null -w "with-token:/api/health HTTP=%{http_code}\n" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-Org-Id: $ORG" \
              "$BASE/api/health" || true
          else
            echo "GRAFANA_API_TOKEN not set (skipping with-token health)"
          fi
