name: healthcheck
on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
jobs:
  ok:
    if: contains(github.event.pull_request.labels.*.name, 'evidence')
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
