name: healthcheck
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Run healthcheck
        run: bash scripts/healthcheck.sh