name: phase0-complete-issue
on:
  push:
    branches: [ "feat/phase0-complete" ]

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Open or update "Phase 0 Complete" issue
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          title="Phase 0 Complete"
          body=$(cat <<'MD'
## Phase 0 Complete — Declaration

### Summary
All Phase 0 steps (1–10) are green and ready for merge:
- ✅ **Step 1-4:** Roles skeleton, Schema, EG-Space, Digest-Nav
- ✅ **Step 5:** CLI run-all pipeline
- ✅ **Step 6:** Healthcheck validation
- ✅ **Step 7:** Metrics collection (coverage/lag)
- ✅ **Step 8:** CI unification + artifacts
- ✅ **Step 9:** README tutorial + STATE update  
- ✅ **Step 10:** Completion documentation

### Evidence
- CI `Phase0-Health` is required and green
- See `docs/PHASE0_COMPLETION.md` for complete evidence links
- Artifacts bundled in `artifacts-phase0`

### Next Phase
Phase 1 preparation: KPI design & PoC architecture for swarm coordination

---
_This issue will be automatically closed when merged to main._
MD
)
          
          # Check if issue already exists
          existing_issue=$(gh issue list --state open --search "$title in:title" --json number --jq '.[0].number // empty')
          
          if [ -z "$existing_issue" ]; then
            echo "Creating new issue..."
            gh issue create --title "$title" --body "$body" --label "milestone:phase0"
          else
            echo "Issue #$existing_issue already exists, adding comment..."
            gh issue comment "$existing_issue" --body "Phase 0 completion branch updated. Ready for review and merge."
          fi