name: PR Guard (pre-DoD)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # 重要変更のときだけ起動（ドキュメント編集やREADMEでは起動しない）
    paths:
      - 'STATE/**'
      - 'infra/**'
      - '.github/workflows/**'
      - '!docs/**'
      - '!README.md'

permissions:
  contents: read

jobs:
  guard:
    # PR本文に context_header: が含まれないときはジョブごとスキップ（=成功扱い）
    if: contains(github.event.pull_request.body || '', 'context_header:')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ここに既存のチェックがあればそのまま残す。無ければ軽いパス表示のみでOK
      - name: Context header present — run guard checks
        run: echo "context_header present; guard checks run."