name: Render Manual (wrapper)

on:
  workflow_dispatch:
    inputs:
      from:
        description: "From"
        required: false
        default: "now-30m"
      to:
        description: "To"
        required: false
        default: "now"

permissions:
  actions: read
  contents: read

concurrency:
  group: render-manual
  cancel-in-progress: false

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Planner OK
        run: |
          echo "planner OK: ${GITHUB_RUN_ID}"

  call-render-inline:
    runs-on: [self-hosted, k8s-runner]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/render-grafana
        with:
          from: ${{ github.event.inputs.from || 'now-30m' }}
          to:   ${{ github.event.inputs.to   || 'now' }}
