name: Render Entrypoint

on:
  push:
    branches: [ manual-render ]
  workflow_dispatch:
    inputs:
      from: { description: "from", required: false, default: "now-30m" }
      to:   { description: "to",   required: false, default: "now" }

jobs:
  bridge:
    runs-on: [self-hosted, k8s-runner]
    env:
      GRAFANA_BASE_URL: ${{ vars.GRAFANA_BASE_URL || 'http://grafana.monitoring.svc.cluster.local' }}
      GRAFANA_API_TOKEN: ${{ secrets.GRAFANA_API_TOKEN }}
      GRAFANA_ORG_ID: ${{ vars.GRAFANA_ORG_ID || '1' }}
    outputs:
      FROM: ${{ steps.set.outputs.FROM }}
      TO:   ${{ steps.set.outputs.TO }}
    steps:
      - uses: actions/checkout@v4
      - id: set
        run: |
          echo "FROM=${{ github.event.inputs.from || 'now-30m' }}" >> "$GITHUB_OUTPUT"
          echo "TO=${{ github.event.inputs.to   || 'now'     }}" >> "$GITHUB_OUTPUT"

  reuse:
    needs: bridge
    uses: ./.github/workflows/render_reusable.yml
    secrets: inherit  # pragma: allowlist secret
    with:
      from: ${{ needs.bridge.outputs.FROM }}
      to:   ${{ needs.bridge.outputs.TO }}
