name: Render Manual (wrapper)

on:
  workflow_dispatch:
    inputs:
      from:
        description: "From"
        required: false
        default: "now-30m"
      to:
        description: "To"
        required: false
        default: "now"

permissions:
  actions: read
  contents: read

concurrency:
  group: render-manual
  cancel-in-progress: false

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Planner OK
        run: |
          echo "planner OK: ${GITHUB_RUN_ID}"
