name: Render Manual (wrapper)
on:
  workflow_dispatch:
    inputs:
      from: { description: "From", required: false, default: "now-30m" }
      to:   { description: "To",   required: false, default: "now" }

jobs:
  call-render:
    uses: HirakuArai/vpm-mini/.github/workflows/render_reusable.yml@main
    secrets: inherit
    with:
      from: ${{ github.event.inputs.from }}
      to:   ${{ github.event.inputs.to }}
