name: Render via push (manual-render)
on:
  push:
    branches: [ manual-render ]
jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      from: ${{ steps.extract.outputs.from }}
      to:   ${{ steps.extract.outputs.to }}
    steps:
      - name: Parse params from commit message
        id: extract
        run: |
          set -euo pipefail
          msg="${{ github.event.head_commit.message }}"
          FROM=$(printf "%s" "$msg" | sed -n 's/.*from=\([^ ]*\).*/\1/p')
          TO=$(printf "%s" "$msg" | sed -n 's/.*to=\([^ ]*\).*/\1/p')
          [ -z "$FROM" ] && FROM="now-30m"
          [ -z "$TO" ] && TO="now"
          echo "from=$FROM" >> "$GITHUB_OUTPUT"
          echo "to=$TO"     >> "$GITHUB_OUTPUT"

  render:
    needs: params
    uses: ./.github/workflows/render_reusable.yml
    with:
      from: ${{ needs.params.outputs.from }}
      to:   ${{ needs.params.outputs.to }}
