name: Render Manual (wrapper)
on:
  workflow_dispatch:
    inputs:
      from: { description: "From", required: false, default: "now-30m" }
      to:   { description: "To",   required: false, default: "now" }

jobs:
  call-render:
    name: Render Grafana manual
    permissions:
      contents: read
    uses: HirakuArai/vpm-mini/.github/workflows/render_reusable.yml@main
    # pass repo secrets to the called workflow
    secrets: "inherit"  # pragma: allowlist secret
    with:
      from: ${{ github.event.inputs.from || 'now-30m' }}
      to:   ${{ github.event.inputs.to   || 'now' }}
