name: Render Entrypoint (manual)
on:
  workflow_dispatch:
    inputs:
      from: { required: false, default: "now-30m" }
      to:   { required: false, default: "now" }
  schedule:
    - cron: "0 22 * * *"   # 07:00 JST（不要なら後で外せます）
jobs:
  render:
    runs-on: [self-hosted, k8s-runner]
    steps:
      - name: Prepare params
        id: prep
        run: |
          FROM="${{ github.event.inputs.from || 'now-30m' }}"
          TO="${{ github.event.inputs.to   || 'now' }}"
          echo "from=$FROM" >> $GITHUB_OUTPUT
          echo "to=$TO"     >> $GITHUB_OUTPUT

      - name: Grafana health
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}" http://grafana.monitoring.svc.cluster.local/api/health)
          echo "HEALTH=$code"; test "$code" = "200"

      - name: Render PNG
        run: |
          BASE="http://grafana.monitoring.svc.cluster.local"
          UID="evidence-prod"
          SLUG="evidence-e28093-prod"
          curl -sS -G "$BASE/render/d-solo/$UID/$SLUG" \
            --data-urlencode "from=${{ steps.prep.outputs.from }}" \
            --data-urlencode "to=${{ steps.prep.outputs.to }}" \
            --data-urlencode "orgId=1" \
            --data-urlencode "panelId=1" \
            --output out.png
          file out.png && test -s out.png

      - name: Footer
        run: echo "== FOOTER == VALIDATE: OK" >> evidence.log

      - uses: actions/upload-artifact@v4
        with:
          name: grafana-render
          path: |
            out.png
            evidence.log
