name: Render Reusable (self-hosted)
on:
  workflow_call:
    inputs:
      from: { type: string, required: false, default: "now-30m" }
      to:   { type: string, required: false, default: "now" }

jobs:
  render:
    name: Render Grafana
    runs-on: [self-hosted, k8s-runner]
    steps:
      - uses: actions/checkout@v4

      - name: Grafana health
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}" http://grafana.monitoring.svc.cluster.local/api/health)
          echo "HEALTH=$code"; test "$code" = "200"

      - name: Render PNG (collect only)
        id: render
        shell: bash
        env:
          INPUT_FROM: ${{ inputs.from }}
          INPUT_TO: ${{ inputs.to }}
        run: |
          set -euo pipefail

          meta=$(cat infra/observability/dashboard_target.json)
          ORG=$(jq -r '.grafana.org'      <<<"$meta")
          DASH_UID=$(jq -r '.grafana.uid' <<<"$meta")
          SLUG_RAW=$(jq -r '.grafana.slug'<<<"$meta")
          PANEL_ID=$(jq -r '.grafana.panelId'<<<"$meta")

          BASE="${GRAFANA_BASE_URL:-http://grafana.monitoring.svc.cluster.local}"
          BASE="${BASE%/}"

          DASH_SLUG=$(jq -rn --arg slug "$SLUG_RAW" '$slug|@uri')

          FROM="${FROM:-${INPUT_FROM:-now-30m}}"
          TO="${TO:-${INPUT_TO:-now}}"
          MIN_PNG_BYTES="${MIN_PNG_BYTES:-512}"

          mkdir -p artifacts
          : > artifacts/evidence.log
          : > artifacts/headers.txt

          URL="${BASE}/render/d-solo/${DASH_UID}/${DASH_SLUG}"
          echo "URL=${URL}" | tee -a artifacts/evidence.log
          echo "PARAMS panelId=${PANEL_ID} from=${FROM} to=${TO} orgId=${ORG}" | tee -a artifacts/evidence.log

          AUTH=()
          if [ -n "${GRAFANA_API_TOKEN:-}" ]; then
            AUTH+=(-H "Authorization: Bearer ${GRAFANA_API_TOKEN}")
          fi

          HTTP=$(curl -sS -w "%{http_code}" \
            "${AUTH[@]}" \
            -H "X-Org-Id: ${ORG}" \
            -G "$URL" \
            --data-urlencode "panelId=${PANEL_ID}" \
            --data-urlencode "from=${FROM}" \
            --data-urlencode "to=${TO}" \
            --data-urlencode "orgId=${ORG}" \
            -D artifacts/headers.txt \
            -o artifacts/out.png || true)

          CT=$(grep -i '^content-type:' artifacts/headers.txt | tr -d '\r' | awk '{print tolower($2)}')
          SIZE=$( (stat -f%z artifacts/out.png 2>/dev/null || stat -c%s artifacts/out.png 2>/dev/null) || echo 0)
          head -c 16 artifacts/out.png | od -An -tx1 | tr -s ' ' > artifacts/png_head.hex

          echo "HTTP=${HTTP} CT=${CT:-n/a} UID=${DASH_UID} panelId=${PANEL_ID} from=${FROM} to=${TO} size=${SIZE}" | tee -a artifacts/evidence.log
          echo "HEADHEX=$(cat artifacts/png_head.hex)" | tee -a artifacts/evidence.log

          PNG_SIG_OK=$(head -c 8 artifacts/out.png | xxd -p | awk '{print tolower($0)}' | grep -q '^89504e47' && echo ok || echo ng)

          if [ "${HTTP}" = "200" ] && echo "${CT}" | grep -q 'image/png' && [ "${PNG_SIG_OK}" = "ok" ] && [ "${SIZE:-0}" -ge "${MIN_PNG_BYTES}" ]; then
            echo "== FOOTER == OK" | tee -a artifacts/evidence.log
            echo "result=ok" >> "$GITHUB_OUTPUT"
          else
            echo "== FOOTER == NG" | tee -a artifacts/evidence.log
            echo "result=ng" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grafana-render
          path: |
            artifacts/out.png
            artifacts/evidence.log
            artifacts/headers.txt
            artifacts/png_head.hex

      - name: Fail if NG
        if: steps.render.outputs.result == 'ng'
        run: |
          echo "::error::Render guard tripped (HTTP/size/type). See artifacts/evidence.log"
          exit 1
