name: Token Guard
on:
  workflow_dispatch: {}
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Verify GH_TOKEN can call Actions API
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -e
          gh --version
          gh api -i /user | sed -n '/^x-oauth-scopes:/Ip' || true
          gh api /repos/${{ github.repository }}/actions/workflows --paginate >/dev/null
          echo "OK: Actions API reachable with GH_TOKEN"
