name: understanding-guard (post)
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  workflow_dispatch:

jobs:
  post:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install pyyaml >/dev/null

      - name: Compute understanding status (always succeed)
        id: status
        run: |
          OUT="$(python tools/understanding_status.py --format summary || true)"
          echo "$OUT"
          parse() { echo "$OUT" | sed -n "s/.*$1=\([^;]*\).*/\1/p"; }
          echo "snapshot=$(parse snapshot)" >> $GITHUB_OUTPUT
          echo "diag_missing=$(parse diag_missing)" >> $GITHUB_OUTPUT
          echo "goals_equal=$(parse goals_equal)" >> $GITHUB_OUTPUT

      - name: Collect dry-run statuses
        id: dry
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          JSON=$(gh api repos/{owner}/{repo}/commits/$SHA/status --jq '[.statuses[] | {context,state}]')
          ok() { echo "$JSON" | jq -r "map(select(.context==\"$1\" and .state==\"success\"))|length"; }
          DG=$(ok "understanding/guard-required")
          DS=$(ok "understanding/snapshot-present")
          DG2=$(ok "understanding/goals-synced")
          echo "dry_guard=$DG" >> $GITHUB_OUTPUT
          echo "dry_snap=$DS" >> $GITHUB_OUTPUT
          echo "dry_goal=$DG2" >> $GITHUB_OUTPUT

      - name: Write Evidence
        id: evidence
        run: |
          SNAPSHOT="${{ steps.status.outputs.snapshot }}"
          DIAG_MISSING="${{ steps.status.outputs.diag_missing }}"
          GOALS_EQUAL="${{ steps.status.outputs.goals_equal }}"
          NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          EVIDENCE="reports/evidence_p3_3_understanding_guard_${{ github.run_id }}.md"
          DRY_GUARD="${{ steps.dry.outputs.dry_guard }}"
          DRY_SNAP="${{ steps.dry.outputs.dry_snap }}"
          DRY_GOAL="${{ steps.dry.outputs.dry_goal }}"
          sed -e "s/{{SNAPSHOT}}/$SNAPSHOT/; s/{{DIAG_MISSING}}/$DIAG_MISSING/; s/{{GOALS_EQUAL}}/$GOALS_EQUAL/; s/{{NOW}}/$NOW/; s/{{DRY_GUARD}}/$DRY_GUARD/; s/{{DRY_SNAP}}/$DRY_SNAP/; s/{{DRY_GOAL}}/$DRY_GOAL/" \
            reports/_understanding_evidence_tpl.md > "$EVIDENCE"
          echo "path=$EVIDENCE" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: evidence-understanding-guard
          path: ${{ steps.evidence.outputs.path }}

      - name: Labels (warn-only)
        if: github.event_name == 'pull_request'
        run: |
          PRNUM="${{ github.event.pull_request.number }}"
          SNAPSHOT="${{ steps.status.outputs.snapshot }}"
          DIAG_MISSING="${{ steps.status.outputs.diag_missing }}"
          GOALS_EQUAL="${{ steps.status.outputs.goals_equal }}"
          add(){ gh pr edit "$PRNUM" --add-label "$1" >/dev/null || true; }
          rmv(){ gh pr edit "$PRNUM" --remove-label "$1" >/dev/null || true; }
          for L in needs-goal-sync needs-snapshot needs-diagnostic; do rmv "$L"; done
          if [ "$GOALS_EQUAL" != "yes" ]; then
            add needs-goal-sync
          fi
          if [ -z "$SNAPSHOT" ] || [ "$SNAPSHOT" = "n/a" ]; then
            add needs-snapshot
          fi
          if [ "$DIAG_MISSING" = "present" ]; then
            add needs-diagnostic
          fi

      - name: Label: ready-for-required
        if: github.event_name == 'pull_request'
        run: |
          PRNUM="${{ github.event.pull_request.number }}"
          DG=${{ steps.dry.outputs.dry_guard }}
          DS=${{ steps.dry.outputs.dry_snap }}
          DG2=${{ steps.dry.outputs.dry_goal }}
          if [ "$DG" = "1" ] && [ "$DS" = "1" ] && [ "$DG2" = "1" ]; then
            gh pr edit "$PRNUM" --add-label ready-for-required >/dev/null || true
          else
            gh pr edit "$PRNUM" --remove-label ready-for-required >/dev/null || true
          fi

      - name: Upsert PR Comment
        if: github.event_name == 'pull_request'
        env:
          SNAPSHOT: ${{ steps.status.outputs.snapshot }}
          DIAG_MISSING: ${{ steps.status.outputs.diag_missing }}
          GOALS_EQUAL: ${{ steps.status.outputs.goals_equal }}
          EVIDENCE_PATH: ${{ steps.evidence.outputs.path }}
          DRY_GUARD: ${{ steps.dry.outputs.dry_guard }}
          DRY_SNAP: ${{ steps.dry.outputs.dry_snap }}
          DRY_GOAL: ${{ steps.dry.outputs.dry_goal }}
        run: tools/ci/upsert_understanding_comment.sh "${{ github.event.pull_request.number }}"

      # 非ブロッキング：終了コード0で完了
