name: understanding-guard
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  guard:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install --quiet pyyaml
      - name: Evaluate understanding
        id: eval
        run: |
          set -euo pipefail
          python tools/understanding_status.py --pr "${PR_NUMBER}" --format json | tee status.json
          SNAP=$(jq -r '.snapshot' status.json)
          MISS=$(jq -r '.diag_missing|length' status.json)
          GOAL=$(jq -r '.goals_equal' status.json)
          echo "snap=$SNAP miss=$MISS goal=$GOAL"
          if [ "$SNAP" = "success" ] && [ "$MISS" -eq 0 ] && [ "$GOAL" = "true" ]; then
            echo "OK"
          else
            echo "NG"
            exit 1
          fi
