name: validate_contracts
on:
  push:
    paths:
      - "contracts/**"
  pull_request:
    paths:
      - "contracts/**"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y yamllint
      - run: yamllint contracts
