apiVersion: v1
kind: Namespace
metadata:
  name: secrets-system
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s-source-store
  namespace: secrets-system
spec:
  provider:
    kubernetes:
      remoteNamespace: secrets-system
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: default